package sumo.login;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.Date;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

import org.hibernate.Session;

import sumo.Constants.Constants;
import sumo.daos.MitarbeiterDao;
import sumo.daos.MitarbeiterstundenDao;
import sumo.mainwindow.Backscreen;
import sumo.mainwindow.MainWindow;
import sumo.model.Mitarbeiter;
import sumo.model.Mitarbeiterstunde;

/*
* Ersteller: Daniel Burgstaller, Thomas Kranzer
* Letzter Bearbeiter: Daniel Burgstaller
* Klassenname: Login
* Superklasse: JFrame
* Interfaces:
* 				ActionListener
* Funktionen:
*				Konstruktor
*				initComponents
*				actionPerformed
*				login
*				Keyevents
*/

public class Login extends JFrame implements ActionListener, KeyListener{
	
	JLabel login_username_label=new JLabel("Username:");
	JLabel login_passwort_label=new JLabel("Passwort:");
	
	JPasswordField login_passwort_passwordfield=new JPasswordField("");
	JTextField login_username_textfield=new JTextField("");
	
	JButton login_login_button=new JButton("Login");
	
	JPanel login_center_panel=new JPanel();
	JPanel login_bottom_panel=new JPanel();
	
	Backscreen backscreen ;
	public static MainWindow mw;
	
	public Login(){
		super("Login");
		setAlwaysOnTop(true);
		setSize(250,130);
		setLocation(550,350);
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setResizable(false);
		setLayout(new BorderLayout());
		
		backscreen= new Backscreen();
		initComponents();
		addKeyListener(this);
		this.setUndecorated(true);
		setVisible(true);
	}//#Konstruktor
	
	
	/*
	* Ersteller: Daniel Burgstaller, Thomas Kranzer
	* Funktionname: initComponents
	* Paramterliste: 
	* Funktion:
	*            Initialisiert die Komponenten des Fensters
	*/
	public void initComponents(){
		/* CenterPanel */
		
		login_center_panel.setLayout(new GridLayout(2, 2,20,20));
		login_center_panel.setBackground(Constants.cl_blue);

		login_username_label.setForeground(Color.WHITE);
		login_center_panel.add(login_username_label);

		login_center_panel.add(login_username_textfield);

		login_passwort_label.setForeground(Color.WHITE);
		login_center_panel.add(login_passwort_label);

		login_center_panel.add(login_passwort_passwordfield);

		add(login_center_panel, BorderLayout.CENTER);
		
		/* BottomPanel */
		login_bottom_panel.setBackground(Constants.cl_blue);
		
		login_login_button.addActionListener(this);
		login_login_button.addKeyListener(this);
																																		
	
		login_bottom_panel.add(login_login_button);

		add(login_bottom_panel,BorderLayout.SOUTH);
		
		this.repaint();
	}//#initComponents

	
	/*
	* Ersteller: Daniel Burgstaller, Thomas Kranzer
	* Funktionname: actionPerformed (autoGenerated)
	* Paramterliste: 
	* 			ActionEvent args - Eventargumente
	* Funktion:
	*            Behandelt die Aktionen des Fensters
	*/
	@Override
	public void actionPerformed(ActionEvent args) {
		String cmd=args.getActionCommand();
		if (cmd.equals("Login")){
			String username=login_username_textfield.getText();
			String passwort=login_passwort_passwordfield.getText();
			login(username,passwort);
			
		}//#if
	}//#actionPerformed

	
	/*
	* Ersteller: Daniel Burgstaller
	* Funktionname: login
	* Paramterliste: 
	* 			username - Benutzername mit dem angemeldet wird
	* 			passwort - Passwort mit dem angemeldet wird
	* Funktion:
	*            versucht den login
	*/
	private void login(String username, String passwort) {
		MitarbeiterDao d=new MitarbeiterDao();
		Mitarbeiter mb=d.getMitarbeiterByUsername(username);
		if (mb.getPasswort().equals(passwort)){
			backscreen.dispose();
			this.dispose();
			
			boolean found=false;
			for (Mitarbeiter m: Constants.loggedInUsers){
				if (m.getUsername().equals(username)){
					found=true;
				}
			}
			if (!found){
				Constants.loggedInUsers.add(mb);
				Mitarbeiterstunde ms=new Mitarbeiterstunde();
				ms.setMitarbeiter(mb);
				Date actual=new Date();
				java.sql.Timestamp angekommen=new java.sql.Timestamp(actual.getTime());
				ms.setAngekommen(angekommen);
				
				MitarbeiterstundenDao dao=new MitarbeiterstundenDao();
				dao.saveOrUpdate(ms);
			}
			mw=new MainWindow(login_username_textfield.getText());
			
		}else{
			JOptionPane.showMessageDialog(this, "Falsches Passwort!");
		}//#if
	}//#login


	@Override
	public void keyTyped(KeyEvent e) {
		// TODO Auto-generated method stub
		
	}//#keyTyped

	/*
	* Ersteller: Thomas Kranzer
	* Funktionname: keyPressed (autoGenerated)
	* Paramterliste: 
	* 			KeyEvent e - Keyeventargument
	* Funktion:
	*            Fängt das die Eingabe von der Tastatur ab, sodass man sich auch mit Enter einloggen kann
	*/
	@Override
	public void keyPressed(KeyEvent e) {
		
		if (e.getKeyCode() == KeyEvent.VK_ENTER){
			String username=login_username_textfield.getText();
			String passwort=login_passwort_passwordfield.getText();
			login(username,passwort);
		}//#if
	}//#keyPressed


	@Override
	public void keyReleased(KeyEvent e) {
		// TODO Auto-generated method stub
		
	}//#keyReleased
	
}//#Login
