alter table ARTIKELAUSGANG drop foreign key FK1DCCBFA6A5B6D7D1;
alter table ARTIKELAUSGANG drop foreign key fk_artikel_artikelausgang;
alter table ARTIKELEINGANG drop foreign key FKDCA50FB18C98C22A;
alter table ARTIKELEINGANG drop foreign key fk_artikel_artikeleingang;
alter table AUSGANGSRECHNUNG drop foreign key FKA018FDF93FD528FB;
alter table DVD drop foreign key FK109F218F93F;
alter table EINGANGSRECHNUNG drop foreign key FK86C28A4E632E6DA2;
alter table EINGANGSRECHNUNG drop foreign key FK86C28A4E494CACE9;
alter table MAHNUNG drop foreign key FK5C462CF43FD528FB;
alter table MITARBEITERSTUNDE drop foreign key FKC1A7833FCD0AF7F9;
alter table PLAYSTATIONSPIEL drop foreign key FKF266EBD318F93F;
alter table VERKAUF drop foreign key FK3FBCE86A3FD528FB;
alter table VERLEIH drop foreign key FK3FBD6A5B3FD528FB;
drop table if exists ARTIKEL;
drop table if exists ARTIKELAUSGANG;
drop table if exists ARTIKELEINGANG;
drop table if exists AUSGANGSRECHNUNG;
drop table if exists DVD;
drop table if exists EINGANGSRECHNUNG;
drop table if exists KASSA;
drop table if exists KUNDE;
drop table if exists LIEFERANT;
drop table if exists MAHNUNG;
drop table if exists MEDIUM;
drop table if exists MITARBEITER;
drop table if exists MITARBEITERSTUNDE;
drop table if exists PLAYSTATIONSPIEL;
drop table if exists RECHNUNG;
drop table if exists VERKAUF;
drop table if exists VERLEIH;
create table ARTIKEL (ID bigint not null, NAME varchar(255), MENGE smallint, PREIS float, KATEGORIE varchar(255), BEMERKUNG varchar(255), STEUERKLASSE smallint, primary key (ID));
create table ARTIKELAUSGANG (ar_id bigint not null, art_id bigint, aa_menge smallint, aa_pos integer not null, primary key (ar_id, aa_pos));
create table ARTIKELEINGANG (er_id bigint not null, art_id bigint, ae_menge smallint, ae_eingangspreis float, ae_pos integer not null, primary key (er_id, ae_pos));
create table AUSGANGSRECHNUNG (ID bigint not null, KUNDE bigint, primary key (ID));
create table DVD (ID bigint not null, SCHAUSPIELER varchar(255), REGISSEUR varchar(255), DREHBUCH varchar(255), INHALT varchar(255), DAUER time, primary key (ID));
create table EINGANGSRECHNUNG (ID bigint not null, LIEFERANT bigint, primary key (ID));
create table KASSA (ID date not null, BESTAND float, primary key (ID));
create table KUNDE (ID bigint not null, NAME varchar(255), ANSCHRIFT varchar(255), PLZ smallint, ORT varchar(255), GUTHABEN float, STATUS varchar(255), LETZTERBESUCH date, USERNAME varchar(255), PASSWORD varchar(255), EMAIL varchar(255), primary key (ID));
create table LIEFERANT (ID bigint not null, NAME varchar(255), ANSCHRIFT varchar(255), PLZ smallint, ORT varchar(255), KONTONR integer, BLZ smallint, BEMERKUNG varchar(255), primary key (ID));
create table MAHNUNG (ID bigint not null, KUNDE bigint, DATUM date, BETRAG float, STUFE smallint, primary key (ID));
create table MEDIUM (ID bigint not null, TITEL varchar(255), MENGE integer, BILDPFAD varchar(255), GENRE varchar(255), AUSLEIHUNGEN integer, PREIS float, ERWERBSDATUM date, TYP smallint, primary key (ID));
create table MITARBEITER (ID bigint not null auto_increment, NAME varchar(255), ANSCHRIFT varchar(255), PLZ smallint, ORT varchar(255), GEHALT float, EINSTIEGSDATUM date, KONTONR bigint, BLZ smallint, USERNAME varchar(255), PASSWORT varchar(255), BEMERKUNG varchar(255), ISADMIN bit, BILDPFAD varchar(255), primary key (ID));
create table MITARBEITERSTUNDE (ID bigint not null auto_increment, MITARBEITER bigint, ANGEKOMMEN date, GEGANGEN date, BEMERKUNG varchar(255), primary key (ID));
create table PLAYSTATIONSPIEL (ID bigint not null, MAXSPIELER integer, primary key (ID));
create table RECHNUNG (ID bigint not null, ZIEL varchar(255), BETRAG double precision, DATUM date, primary key (ID));
create table VERKAUF (ID bigint not null, GESAMTBETRAG float, DATUM date, ZIEL varchar(255), KUNDE bigint, primary key (ID));
create table VERLEIH (ID bigint not null, DATUMVON date, DATUMBIS date, KUNDE bigint, BEMERKUNG varchar(255), primary key (ID));
alter table ARTIKELAUSGANG add index FK1DCCBFA6A5B6D7D1 (ar_id), add constraint FK1DCCBFA6A5B6D7D1 foreign key (ar_id) references AUSGANGSRECHNUNG (ID);
alter table ARTIKELAUSGANG add index fk_artikel_artikelausgang (art_id), add constraint fk_artikel_artikelausgang foreign key (art_id) references ARTIKEL (ID);
alter table ARTIKELEINGANG add index FKDCA50FB18C98C22A (er_id), add constraint FKDCA50FB18C98C22A foreign key (er_id) references EINGANGSRECHNUNG (ID);
alter table ARTIKELEINGANG add index fk_artikel_artikeleingang (art_id), add constraint fk_artikel_artikeleingang foreign key (art_id) references ARTIKEL (ID);
alter table AUSGANGSRECHNUNG add index FKA018FDF93FD528FB (KUNDE), add constraint FKA018FDF93FD528FB foreign key (KUNDE) references KUNDE (ID);
alter table DVD add index FK109F218F93F (ID), add constraint FK109F218F93F foreign key (ID) references MEDIUM (ID);
alter table EINGANGSRECHNUNG add index FK86C28A4E632E6DA2 (ID), add constraint FK86C28A4E632E6DA2 foreign key (ID) references RECHNUNG (ID);
alter table EINGANGSRECHNUNG add index FK86C28A4E494CACE9 (LIEFERANT), add constraint FK86C28A4E494CACE9 foreign key (LIEFERANT) references LIEFERANT (ID);
alter table MAHNUNG add index FK5C462CF43FD528FB (KUNDE), add constraint FK5C462CF43FD528FB foreign key (KUNDE) references KUNDE (ID);
alter table MITARBEITERSTUNDE add index FKC1A7833FCD0AF7F9 (MITARBEITER), add constraint FKC1A7833FCD0AF7F9 foreign key (MITARBEITER) references MITARBEITER (ID);
alter table PLAYSTATIONSPIEL add index FKF266EBD318F93F (ID), add constraint FKF266EBD318F93F foreign key (ID) references MEDIUM (ID);
alter table VERKAUF add index FK3FBCE86A3FD528FB (KUNDE), add constraint FK3FBCE86A3FD528FB foreign key (KUNDE) references KUNDE (ID);
alter table VERLEIH add index FK3FBD6A5B3FD528FB (KUNDE), add constraint FK3FBD6A5B3FD528FB foreign key (KUNDE) references KUNDE (ID);
